name: 000-Build-Docker-images

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/000-setup/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/000-setup/**"
  
jobs:

  build:
    
    runs-on: ubuntu-latest
    # Run only on the given folder
    # defaults:
    #   run:
    #     working-directory: Labs/000-setup
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    # Build the docker images for the setup process
    steps:
    
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
      
      # Add docker multiplatform build
      - name: Set up qemu Action
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out the code
        uses: actions/checkout@v4
      
      # - name: docker-compose Build Action
      #   uses: hoverkraft-tech/compose-action@v2.0.0
      #   with:
      #     compose-file: Labs/000-setup/docker-compose-build.yaml
      
      - name: docker-compose Build Action
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f Labs/000-setup/docker-compose-build.yaml build
      
      - name: docker-compose Push Action
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f Labs/000-setup/docker-compose-build.yaml push
      
        # - name: docker-compose Push Action
        # uses: hoverkraft-tech/compose-action@v2.0.0
        # with:
        #   compose-file: Labs/000-setup/docker-compose-build.yaml
        #   compose-flags: push

      # - name: Build the docker images
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: devopslive/escape-room-bash
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max  

      # - name: Build docker-compose images
      #   working-directory: ./Labs/000-setup
      #   run: docker-compose -f docker-compose-build.yaml build
          
      # - name: Push docker-compose images
      #   working-directory: ./Labs/000-setup
      #   run: docker-compose -f docker-compose-build.yaml push
    
    # build-with-docker:
    # name: Build multi-platform Docker image
    # runs-on: ubuntu-20.04
    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: docker/setup-qemu-action@v3
    #   - uses: docker/setup-buildx-action@v3
    #   - uses: docker/login-action@v3
    #     with:
    #       username: devopslive
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #   - uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       platforms: linux/amd64,linux/arm64
    #       push: true
    #       tags: devopslive/escape-room-bash
    #       cache-from: type=gha
    #       cache-to: type=gha,mode=max     