name: 004a-facts-playbook

on:
  push:
    branches: ["main"]
    paths:
      - "**/Labs/005-facts/004a-facts-playbook/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Labs/005-facts/004a-facts-playbook/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Labs/005-facts/004a-facts-playbook
        run: bash ./_demo.sh
