name: 006-02-create-git-repository

on:
  push:
    branches: ["main"]
    paths:
      - "**/Labs/006-git/006-02-create-git-repository/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Labs/006-git/006-02-create-git-repository/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Labs/006-git/006-02-create-git-repository
        run: bash ./_demo.sh
