name: 006a-create-user

on:
  push:
    branches: ["main"]
    paths:
      - "**/Labs/006a-create-user/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Labs/006a-create-user/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Labs/006a-create-user
        run: bash ./_demo.sh
