name: 009-roles

on:
  push:
    branches: ["main"]
    paths:
      - "**/Labs/009-roles/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Labs/009-roles/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Labs/009-roles
        run: bash ./_demo.sh
